language: go
go:
  - 1.8.x
services:
  - mongodb
install:
  - export PATH=$HOME/gopath/src/github.com/ildarusmanov:$PATH
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - go test -cpu=1,2 -v ./models/ ./controllers/ ./user

